# Generated by Django 3.0.6 on 2020-05-29 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ground_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_type', models.CharField(blank=True, max_length=15)),
                ('description', models.CharField(max_length=30)),
                ('total_area', models.IntegerField(blank=True)),
                ('area_to_repair', models.IntegerField(blank=True)),
                ('unused_area', models.IntegerField(blank=True)),
                ('total_surface_area', models.IntegerField(blank=True)),
                ('remarks', models.TextField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=20)),
                ('tsc_no', models.CharField(blank=True, max_length=10)),
                ('dob', models.DateField(blank=True)),
                ('designation', models.CharField(blank=True, max_length=10)),
                ('job_group', models.CharField(blank=True, max_length=10)),
                ('dofa', models.DateField(blank=True)),
                ('id_no', models.IntegerField(blank=True)),
                ('kra_pin', models.IntegerField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'FEMALE'), ('M', 'MALE'), ('I', 'INTERSEX')], max_length=3)),
                ('contact', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Structure_Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('struct_type', models.CharField(blank=True, max_length=15)),
                ('description', models.CharField(max_length=30)),
                ('total_quantity', models.IntegerField(blank=True)),
                ('quantity_to_repair', models.IntegerField(blank=True)),
                ('quantity_to_replace', models.IntegerField(blank=True)),
                ('unused_quantity', models.IntegerField(blank=True)),
                ('total_surface_area', models.IntegerField(blank=True)),
                ('remarks', models.TextField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_no', models.CharField(blank=True, max_length=20)),
                ('adm_date', models.DateField(blank=True)),
                ('class_on_adm_day', models.IntegerField()),
                ('dob', models.DateField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'FEMALE'), ('M', 'MALE'), ('I', 'INTERSEX')], max_length=3)),
                ('full_name', models.CharField(blank=True, max_length=40)),
                ('guardian_name', models.CharField(blank=True, max_length=40)),
                ('home_address', models.CharField(blank=True, max_length=20)),
                ('last_school', models.CharField(blank=True, choices=[('D', 'DAY'), ('B', 'BORDER')], max_length=50)),
                ('excempted_from_religious_instr', models.CharField(blank=True, max_length=10)),
                ('leaving_date', models.DateField(blank=True)),
                ('leaving_cert_no', models.CharField(blank=True, max_length=15)),
                ('remarks', models.TextField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('dob', models.DateField(blank=True, null=True)),
                ('contact', models.CharField(max_length=15)),
                ('id_no', models.IntegerField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
