# Generated by Django 3.0.6 on 2020-05-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='border_or_day',
            field=models.CharField(blank=True, choices=[('D', 'DAY'), ('B', 'BORDER')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_school',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
