# Generated by Django 3.0.6 on 2020-05-29 08:24

from django.db import migrations
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20200529_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=partial_date.fields.PartialDateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dob',
            field=partial_date.fields.PartialDateField(blank=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dofa',
            field=partial_date.fields.PartialDateField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='adm_date',
            field=partial_date.fields.PartialDateField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='leaving_date',
            field=partial_date.fields.PartialDateField(blank=True),
        ),
    ]
