# Generated by Django 3.0.6 on 2020-05-29 08:28

from django.db import migrations
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20200529_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=partial_date.fields.PartialDateField(blank=True),
        ),
    ]
