# Generated by Django 3.0.6 on 2020-05-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20200529_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ground_inventory',
            name='remarks',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='structure_inventory',
            name='remarks',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='remarks',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
