# Generated by Django 3.0.6 on 2020-06-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_school_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ground_inventory',
            name='item_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structure_inventory',
            name='item_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
