# Generated by Django 3.0.6 on 2020-06-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_auto_20200601_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='id_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
