# Generated by Django 3.0.6 on 2020-06-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_auto_20200601_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ground_inventory',
            name='item_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structure_inventory',
            name='item_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
