# Generated by Django 3.0.6 on 2020-06-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_auto_20200601_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
